[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.16'
optimizer = true
optimizer_runs = 20000
via_ir = false

[rpc_endpoints]
arb1 = "https://arb1.arbitrum.io/rpc"
arbgoerli = "https://goerli-rollup.arbitrum.io/rpc"
arbnova = "https://nova.arbitrum.io/rpc"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config